// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBI_MF.Data;

namespace SBI_MF.Migrations
{
    [DbContext(typeof(SBIMFDbContext))]
    [Migration("20211216074552_masterTableCreation")]
    partial class masterTableCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SBI_MF.Model.ChargeModel", b =>
                {
                    b.Property<string>("ChargeId")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("ChargeName")
                        .HasColumnType("Varchar(50)");

                    b.Property<decimal>("ChargeValue")
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("SchemeType")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("Varchar(50)");

                    b.HasKey("ChargeId");

                    b.ToTable("ChargeMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.CounterPartyModel", b =>
                {
                    b.Property<string>("CounterPartyID")
                        .HasColumnType("varchar(15)");

                    b.Property<int>("AccountNo")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("BankBranch")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CounterpartyName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId1")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId2")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxNo1")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxNo2")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GSTNo")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("IFSC")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobNo1")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobNo2")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameBeneficiary")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PAN")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TelNo1")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelNo2")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CounterPartyID");

                    b.ToTable("CounterPartyMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.CustodianModel", b =>
                {
                    b.Property<string>("CustodianId")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustodianName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId1")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailId2")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxNumber1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FaxNumber2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MobileNumber1")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MobileNumber2")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TelephoneNumber1")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TelephoneNumber2")
                        .HasColumnType("varchar(15)");

                    b.HasKey("CustodianId");

                    b.ToTable("CustodianMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.GoldLocModel", b =>
                {
                    b.Property<string>("Lid")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("GoldLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.ToTable("GoldLocationMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.GoldModel", b =>
                {
                    b.Property<string>("GoldId")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Active")
                        .HasColumnType("char(1)");

                    b.Property<float>("BarWeightInGrams")
                        .HasColumnType("real");

                    b.Property<float>("BarWeightInKg")
                        .HasColumnType("real");

                    b.Property<decimal>("CGST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("CommodityDenomination")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("CommodityPurity")
                        .HasColumnType("numeric(20,4)");

                    b.Property<decimal>("Conversionfactor")
                        .HasColumnType("numeric(20,4)");

                    b.Property<string>("CounterpartyShipper")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("CustomDuty")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("Facevalue")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("FixingCharge")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("GST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Issuer")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("NAVlot")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("Octroi")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("Premium")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("SGST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("SecurityLocation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecurityName")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Stampduty")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("StockExchange")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ValuationRateType")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("VaultingAgent")
                        .HasColumnType("varchar(50)");

                    b.HasKey("GoldId");

                    b.ToTable("GoldMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.TaxesModel", b =>
                {
                    b.Property<string>("TaxId")
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("CGST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("GST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<decimal>("SGST")
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaxId");

                    b.ToTable("TaxMaster");
                });

            modelBuilder.Entity("SBI_MF.Model.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ModuleRights")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Roles")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserGroup")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
